# Change these first
owner: r0manu3l # Your GitHub organization or username, where this repository lives
repo: partner-monitoring # The name of this repository

sites:
  - name: Moviired
    url: $MOVII_URL
    method: POST
    headers:
      - 'Authorization: "Basic dGVzdDp0ZXN0"'
      - 'Content-Type: "application/x-www-form-urlencoded"'
    body: 'grant_type: "client_credentials"'
    expectedStatusCodes:
      - 415
      - 400
      - 401
  - name: Sistarbanc
    url: $MOVII_URL
    method: POST
    headers:
      - 'Authorization: "Basic dGVzdDp0ZXN0"'
      - 'Content-Type: "application/x-www-form-urlencoded"'
    body: 'grant_type: "client_credentials"'
    expectedStatusCodes:
      - 415
      - 400
      - 401
  - name: STP
    url: $MOVII_URL
    method: POST
    headers:
      - 'Authorization: "Basic dGVzdDp0ZXN0"'
      - 'Content-Type: "application/x-www-form-urlencoded"'
    body: 'grant_type: "client_credentials"'
    expectedStatusCodes:
      - 415
      - 400
      - 401
  - name: Pagadito
    url: $MOVII_URL
    method: POST
    headers:
      - 'Authorization: "Basic dGVzdDp0ZXN0"'
      - 'Content-Type: "application/x-www-form-urlencoded"'
    body: 'grant_type: "client_credentials"'
    expectedStatusCodes:
      - 415
      - 400
      - 401
  - name: Kashio
    url: $MOVII_URL
    method: POST
    headers:
      - 'Authorization: "Basic dGVzdDp0ZXN0"'
      - 'Content-Type: "application/x-www-form-urlencoded"'
    body: 'grant_type: "client_credentials"'
    expectedStatusCodes:
      - 415
      - 400
      - 401
  - name: Pago TIC
    url: $MOVII_URL
    method: POST
    headers:
      - 'Authorization: "Basic dGVzdDp0ZXN0"'
      - 'Content-Type: "application/x-www-form-urlencoded"'
    body: 'grant_type: "client_credentials"'
    expectedStatusCodes:
      - 415
      - 400
      - 401
  - name: Local Payment
    url: $MOVII_URL
    method: POST
    headers:
      - 'Authorization: "Basic dGVzdDp0ZXN0"'
      - 'Content-Type: "application/x-www-form-urlencoded"'
    body: 'grant_type: "client_credentials"'
    expectedStatusCodes:
      - 415
      - 400
      - 401
      
assignees: # Users to assign downtime issues (optional)
  - r0manu3l

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /partner-monitoring
  logoUrl: https://inswitchpublic2.s3.amazonaws.com/inswitch_logo.png
  name: Inswhub Platform - Partners
  introTitle: "**Monitoring** Inswitch Partners."
  introMessage: POC - Project
  #navbar:
    #- title: Status
      #href: /
    #- title: GitHub
      #href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
